//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaboration
    {
        public int Id { get; set; }
        public string Board_Id { get; set; }
        public int Uid { get; set; }
        public int Permission { get; set; }
    
        public virtual Visual_Boards Visual_Boards { get; set; }
        public virtual User User { get; set; }
    }
}
