//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notepad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notepad()
        {
            this.NoteContents = new HashSet<NoteContent>();
        }
    
        public int Id { get; set; }
        public string Notepad_Id { get; set; }
        public int Uid { get; set; }
        public Nullable<int> Tag_Id { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteContent> NoteContents { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
