//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalVault
    {
        public int Vault_Id { get; set; }
        public int Uid { get; set; }
        public string PlatformName { get; set; }
        public string AccountMail { get; set; }
        public string AccountPassword { get; set; }
        public string Username { get; set; }
        public string AlternativeMail { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
    }
}
