//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Task_Id { get; set; }
        public int Uid { get; set; }
        public string Short_Description { get; set; }
        public System.DateTime Creation_Time { get; set; }
        public Nullable<System.DateTime> Target_Time { get; set; }
        public int Status { get; set; }
        public string Icon { get; set; }
    
        public virtual User User { get; set; }
    }
}
